application: samueldillow-com
runtime    : python27
api_version: 1
threadsafe : yes
libraries:
    -
        name   : jinja2
        version: 2.6
handlers   :
    -
        url   : /.*
        script: runner.run
